// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrientationRetake.Database;

namespace OrientationRetake.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211126103332_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("OrientationRetake.Models.Entities.Climber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Altitude")
                        .HasColumnType("int");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("MountainId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MountainId");

                    b.ToTable("Climbers");
                });

            modelBuilder.Entity("OrientationRetake.Models.Entities.Mountain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstClimbed")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("MountName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mountains");
                });

            modelBuilder.Entity("OrientationRetake.Models.Entities.Climber", b =>
                {
                    b.HasOne("OrientationRetake.Models.Entities.Mountain", "Mountain")
                        .WithMany("ClimbedClimbers")
                        .HasForeignKey("MountainId");

                    b.Navigation("Mountain");
                });

            modelBuilder.Entity("OrientationRetake.Models.Entities.Mountain", b =>
                {
                    b.Navigation("ClimbedClimbers");
                });
#pragma warning restore 612, 618
        }
    }
}
